version: '3.8'

services:
  video-overlay:
    build: .
    container_name: video-graphic-overlay
    restart: unless-stopped
    ports:
      - "5000:5000/udp"
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./examples:/app/examples:ro
      - ./logs:/app/logs
    environment:
      - LOG_LEVEL=info
    networks:
      - video-network
    healthcheck:
      test: ["CMD", "pgrep", "video-overlay"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Optional: VLC for testing UDP output
  vlc-test:
    image: jess/vlc
    container_name: vlc-test
    depends_on:
      - video-overlay
    networks:
      - video-network
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: vlc udp://@video-overlay:5000
    profiles:
      - testing

  # Optional: FFmpeg for testing and monitoring
  ffmpeg-monitor:
    image: jrottenberg/ffmpeg:4.4-alpine
    container_name: ffmpeg-monitor
    depends_on:
      - video-overlay
    networks:
      - video-network
    command: >
      ffmpeg -i udp://video-overlay:5000 
      -c copy 
      -f null -
    profiles:
      - testing

networks:
  video-network:
    driver: bridge

volumes:
  logs:
    driver: local
