input:
  hls_url: "https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8"
  buffer_size: 1048576
  connection_retry: 3
  timeout: 30
  source_type: "playbin3"  # Use playbin3 for automatic HLS handling

output:
  host: "127.0.0.1"
  port: 5000
  bitrate: 2000000
  video_codec: "h264"
  audio_codec: "aac"
  format: "mpegts"

overlay:
  enabled: true
  type: "text"
  text:
    content: "PLAYBIN3 STREAM - {{.time}}"
    font_size: 32
    font_family: "Arial Bold"
    color: "white"
    background: "rgba(0,0,150,0.8)"
  position:
    x: 20
    y: 20
    anchor: "top-left"

pipeline:
  buffer_time: 200
  latency_ms: 100
  sync_on_clock: true
  drop_on_latency: true
